/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Logica.DecodificadorADN;
import javax.swing.JOptionPane;

/**
 *
 * @author joel
 */
public class IngresoGUI extends javax.swing.JDialog {

    private String cadena1 = "";
    private String cadena2 = "";
    
    public IngresoGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compararCadenasButton = new javax.swing.JButton();
        cadena1textField = new javax.swing.JTextField();
        cadena2textField = new javax.swing.JTextField();
        resultadoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        compararCadenasButton.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        compararCadenasButton.setText("Comparar cadenas");
        compararCadenasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compararCadenasButtonActionPerformed(evt);
            }
        });

        cadena1textField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cadena1textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cadena1textFieldKeyTyped(evt);
            }
        });

        cadena2textField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cadena2textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cadena2textFieldKeyTyped(evt);
            }
        });

        resultadoTextField.setEditable(false);
        resultadoTextField.setBackground(new java.awt.Color(0, 0, 0));
        resultadoTextField.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        resultadoTextField.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadena 1");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadena 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compararCadenasButton)
                    .addComponent(resultadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadena1textField)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadena2textField)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadena1textField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadena2textField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(compararCadenasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(resultadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo sirve para que solo se ingresen letras
     * @param evt 
     */
    private void cadena1textFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadena1textFieldKeyTyped
        char validar = evt.getKeyChar();

        if (!Character.isLetter(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo ingresar letras");
        }
    }//GEN-LAST:event_cadena1textFieldKeyTyped

    /**
     * Este metodo sirve para que solo se ingresen letras
     * @param evt 
     */
    private void cadena2textFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadena2textFieldKeyTyped
        char validar = evt.getKeyChar();

        if (!Character.isLetter(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo ingresar letras");
        }
    }//GEN-LAST:event_cadena2textFieldKeyTyped

    private void compararCadenasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compararCadenasButtonActionPerformed
        cadena1 = cadena1textField.getText();
        cadena2 = cadena2textField.getText();
        
        if (cadenaPermitida()) {
            JOptionPane.showMessageDialog(this, "Cadena muy corta");
        }
        else{     
            DecodificadorADN decodificadorADN = new DecodificadorADN(cadena1, cadena2);
            resultadoTextField.setText(decodificadorADN.ejecutarDecodificador());
            
            //Limpiar los text field
            cadena1textField.setText("");
            cadena2textField.setText("");
        }
    }//GEN-LAST:event_compararCadenasButtonActionPerformed

    public boolean cadenaPermitida(){
        return (cadena1.length()<2 || cadena2.length()<2);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cadena1textField;
    private javax.swing.JTextField cadena2textField;
    private javax.swing.JButton compararCadenasButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultadoTextField;
    // End of variables declaration//GEN-END:variables
}
